apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-azure-storage-account
  namespace: default
spec:
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: stefsacontainerapp
  - name: accountKey
    secretKeyRef:
      name: DaprAzureStorageAccountKey
      key: DaprAzureStorageAccountKey
  - name: containerName
    value: containerconsole

auth:
  secretStore: local-secret-store
  #secretStore: secretstores.local.env